### ISSUE TITLE
有些轨迹预测的问题想向您请教

### ISSUE THREAD

**Issue by dodeokwangyooo** [TommyGong08/LSTM_Trajectory_Prediction#1]
我在北交读研，有什么好的第一人称视角的项目能推荐一下么？谢谢您

**Comment by TommyGong08** [comment]
您好，轨迹预测方面我有不错的项目，您是否有兴趣，我们可以一起合作，联系方式可以与我邮件联系。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dodeokwangyooo ***@***.***&gt;
发送时间: 2021年9月6日 15:33
收件人: TommyGong08/LSTM_Trajectory_Prediction ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[TommyGong08/LSTM_Trajectory_Prediction] 有些轨迹预测的问题想向您请教 (#1)





 
我在北交读研，有什么好的第一人称视角的项目能推荐一下么？谢谢您
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GongHailong08** [comment]
> 我在北交读研，有什么好的第一人称视角的项目能推荐一下么？谢谢您

您好，轨迹预测方面我有不错的项目，您是否有兴趣，我们可以一起合作，可以与我主页的邮件联系。
